### ISSUE TITLE
请问是停用了吗。。

### ISSUE THREAD

**Issue by errorlife** [textproofreading/cuobiezi_http_api#2]
这是 CuoBieZi.net 的测试账户，有人恶意调用本接口，暂时停用！

**Comment by textproofreading** [comment]
你好， 接口恢复使用了！

**Comment by HuBlanker** [comment]
hi，我测试了postman调用以及java代码调用。使用tester都不可以，请问有什么其他方式可以测试一下效果吗？调用量很少，主要是测试一下效果。
@textproofreading
